# -*- coding: utf-8 -*-
# Generated by Django - Initial migration for baseTemplate
# This file was missing and has been recreated to fix migration dependency

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # This is an empty initial migration
        # The actual models will be created by subsequent migrations
    ]
